const ipsumLorems = {
  1: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, mauris ac tincidunt ultrices, nunc nisl tristique nunc, nec aliquam nunc justo ac nunc. Nulla facilisi. Sed vitae semper nunc. Fusce auctor, nisl a lacinia aliquet, nunc nisl tincidunt nunc, nec aliquam nunc justo ac nunc.`,
  2: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, mauris ac tincidunt ultrices, nunc nisl tristique nunc, nec aliquam nunc justo ac nunc. Nulla facilisi. Sed vitae semper nunc. Fusce auctor, nisl a lacinia aliquet, nunc nisl tincidunt nunc, nec aliquam nunc justo ac nunc.`,
  3: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, mauris ac tincidunt ultrices, nunc nisl tristique nunc, nec aliquam nunc justo ac nunc. Nulla facilisi. Sed vitae semper nunc. Fusce auctor, nisl a lacinia aliquet, nunc nisl tincidunt nunc, nec aliquam nunc justo ac nunc.`,
  4: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, mauris ac tincidunt ultrices, nunc nisl tristique nunc, nec aliquam nunc justo ac nunc. Nulla facilisi. Sed vitae semper nunc. Fusce auctor, nisl a lacinia aliquet, nunc nisl tincidunt nunc, nec aliquam nunc justo ac nunc.`,
  5: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, mauris ac tincidunt ultrices, nunc nisl tristique nunc, nec aliquam nunc justo ac nunc. Nulla facilisi. Sed vitae semper nunc. Fusce auctor, nisl a lacinia aliquet, nunc nisl tincidunt nunc, nec aliquam nunc justo ac nunc.`,
  6: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, mauris ac tincidunt ultrices, nunc nisl tristique nunc, nec aliquam nunc justo ac nunc. Nulla facilisi. Sed vitae semper nunc. Fusce auctor, nisl a lacinia aliquet, nunc nisl tincidunt nunc, nec aliquam nunc justo ac nunc.`,1: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, mauris ac tincidunt ultrices, nunc nisl tristique nunc, nec aliquam nunc justo ac nunc. Nulla facilisi. Sed vitae semper nunc. Fusce auctor, nisl a lacinia aliquet, nunc nisl tincidunt nunc, nec aliquam nunc justo ac nunc.`,
  7: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, mauris ac tincidunt ultrices, nunc nisl tristique nunc, nec aliquam nunc justo ac nunc. Nulla facilisi. Sed vitae semper nunc. Fusce auctor, nisl a lacinia aliquet, nunc nisl tincidunt nunc, nec aliquam nunc justo ac nunc.`,
  8: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, mauris ac tincidunt ultrices, nunc nisl tristique nunc, nec aliquam nunc justo ac nunc. Nulla facilisi. Sed vitae semper nunc. Fusce auctor, nisl a lacinia aliquet, nunc nisl tincidunt nunc, nec aliquam nunc justo ac nunc.`,1: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, mauris ac tincidunt ultrices, nunc nisl tristique nunc, nec aliquam nunc justo ac nunc. Nulla facilisi. Sed vitae semper nunc. Fusce auctor, nisl a lacinia aliquet, nunc nisl tincidunt nunc, nec aliquam nunc justo ac nunc.`,
  9: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, mauris ac tincidunt ultrices, nunc nisl tristique nunc, nec aliquam nunc justo ac nunc. Nulla facilisi. Sed vitae semper nunc. Fusce auctor, nisl a lacinia aliquet, nunc nisl tincidunt nunc, nec aliquam nunc justo ac nunc.`,
  10: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, mauris ac tincidunt ultrices, nunc nisl tristique nunc, nec aliquam nunc justo ac nunc. Nulla facilisi. Sed vitae semper nunc. Fusce auctor, nisl a lacinia aliquet, nunc nisl tincidunt nunc, nec aliquam nunc justo ac nunc.`,1: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, mauris ac tincidunt ultrices, nunc nisl tristique nunc, nec aliquam nunc justo ac nunc. Nulla facilisi. Sed vitae semper nunc. Fusce auctor, nisl a lacinia aliquet, nunc nisl tincidunt nunc, nec aliquam nunc justo ac nunc.`,
  11: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, mauris ac tincidunt ultrices, nunc nisl tristique nunc, nec aliquam nunc justo ac nunc. Nulla facilisi. Sed vitae semper nunc. Fusce auctor, nisl a lacinia aliquet, nunc nisl tincidunt nunc, nec aliquam nunc justo ac nunc.`,
  12: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, mauris ac tincidunt ultrices, nunc nisl tristique nunc, nec aliquam nunc justo ac nunc. Nulla facilisi. Sed vitae semper nunc. Fusce auctor, nisl a lacinia aliquet, nunc nisl tincidunt nunc, nec aliquam nunc justo ac nunc.`,
};

export default ipsumLorems;
